import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Luciana',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'José',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

    products: [
      {
        name: 'Vestido Rendado Branco',
        category: 'Vestido',
        image: './Assets/03.jfif',
        price: 120,
        countInStock: 10,
        brand: 'GrifAfro',
        rating: 4.5,
        numReviews: 10,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
      {
        name: 'Vestido Rendado Vermelho',
        category: 'Vestido',
        image: './Assets/03.jfif',
        price: 100,
        countInStock: 20,
        brand: 'GrifAfro',
        rating: 4.0,
        numReviews: 10,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
      {
        name: 'Vestido Rendado Roxo',
        category: 'Vestido',
        image: './Assets/03.jfif',
        price: 220,
        countInStock: 0,
        brand: 'GrifAfro',
        rating: 4.8,
        numReviews: 17,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
      {
        name: 'Vestido Rendado Cinza',
        category: 'Vestido',
        image: './Assets/04.jfif',
        price: 78,
        countInStock: 15,
        brand: 'GrifAfro',
        rating: 4.5,
        numReviews: 14,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
      {
        name: 'Vestido Rendado Azul',
        category: 'Vestido',
        image: './Assets/05.jfif',
        price: 65,
        countInStock: 5,
        brand: 'GrifAfro',
        rating: 4.5,
        numReviews: 10,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
      {
        name: 'Vestido Rendado Verde',
        category: 'Vestido',
        image: './Assets/06.jfif',
        price: 139,
        countInStock: 12,
        brand: 'GrifAfro',
        rating: 4.5,
        numReviews: 15,
        description: 'Produto de alta qualidade, feito sob medida.',
      },
    ],
  };
  export default data;